name: "GitHub to JIRA Issue Sync"
description: "Performs simple one way syncing of GitHub issues into JIRA."
branding:
  icon: "fast-forward"
  color: "green"
inputs:
  cron_job:
    description: >
      Whether the action is run as a cron job.
      Set true to trigger syncing of new PRs.
    required: false
  sync_label:
    description: >
      Require a specific label to be present to enable syncing to Jira.
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
